version: '3.1'
services:
  db:
    image: postgres
    restart: always
  postgresql_for_homework:
    image: postgres:13
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=12345678